// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxiLxvIFmzqm37xuYMAdu8UBfAR_oDTyM',
    appId: '1:756158976086:android:f896b537014ce53f4debf7',
    messagingSenderId: '756158976086',
    projectId: 'geomsg-4d728',
    storageBucket: 'geomsg-4d728.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSs3uKuLP3pQfDC2Yc32ID2puQOXxwoA',
    appId: '1:756158976086:web:d309e32892d6f5b44debf7',
    messagingSenderId: '756158976086',
    projectId: 'geomsg-4d728',
    authDomain: 'geomsg-4d728.firebaseapp.com',
    storageBucket: 'geomsg-4d728.firebasestorage.app',
    measurementId: 'G-S2XKLE6VQR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxAd_i2uWO3K-Q-HuVmfE0SeYgqMW7RI',
    appId: '1:756158976086:ios:41878acd9bfa28084debf7',
    messagingSenderId: '756158976086',
    projectId: 'geomsg-4d728',
    storageBucket: 'geomsg-4d728.firebasestorage.app',
    androidClientId: '756158976086-8lpc7cmecqv8179111hb5tpre12ke5gv.apps.googleusercontent.com',
    iosClientId: '756158976086-2u82qpdpleks7aq7q6762p257buu36ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.geomsgChat',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACxAd_i2uWO3K-Q-HuVmfE0SeYgqMW7RI',
    appId: '1:756158976086:ios:69030a5373911e164debf7',
    messagingSenderId: '756158976086',
    projectId: 'geomsg-4d728',
    storageBucket: 'geomsg-4d728.firebasestorage.app',
    androidClientId: '756158976086-8lpc7cmecqv8179111hb5tpre12ke5gv.apps.googleusercontent.com',
    iosClientId: '756158976086-es2fci134t9u4prfh9755mclk04up5eb.apps.googleusercontent.com',
    iosBundleId: 'net.looqn.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmSs3uKuLP3pQfDC2Yc32ID2puQOXxwoA',
    appId: '1:756158976086:web:942a1c854da40f7c4debf7',
    messagingSenderId: '756158976086',
    projectId: 'geomsg-4d728',
    authDomain: 'geomsg-4d728.firebaseapp.com',
    storageBucket: 'geomsg-4d728.firebasestorage.app',
    measurementId: 'G-C02QMHPDB7',
  );

}